/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiChatDrawer: typeof import('./components/ai-chat/AiChatDrawer.vue')['default']
    AirQualityChart: typeof import('./components/charts/AirQualityChart.vue')['default']
    DataCard: typeof import('./components/cards/DataCard.vue')['default']
    ForecastChart: typeof import('./components/charts/ForecastChart.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NInput: typeof import('naive-ui')['NInput']
    RadarMap: typeof import('./components/map/RadarMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemperatureChart: typeof import('./components/charts/TemperatureChart.vue')['default']
    WarningList: typeof import('./components/cards/WarningList.vue')['default']
    WindRoseChart: typeof import('./components/charts/WindRoseChart.vue')['default']
  }
}
